name: food_delivery
description: "Food Delivery App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
#  firebase_core: ^3.3.0
#  firebase_auth: ^5.1.4
#  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/burgers/
    - lib/images/sides/
    - lib/images/salads/
    - lib/images/drinks/
    - lib/images/desserts/

  # Uncomment and customize the following lines if you are using custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
